spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:mysql://localhost:3306/patient-service
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 9191

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka
  
